DATA_FILE = "data/orders.json"

DEFAULT_TAX_BR = 0.12
DEFAULT_TAX_US = 0.07
DEFAULT_TAX_OTHER = 0.10

EXPRESS_SHIPPING_BR = 35
EXPRESS_SHIPPING_US = 60
REGULAR_SHIPPING = 15

VIP_SEGMENT = "vip"
HIGH_VALUE_LIMIT = 2000
MEDIUM_VALUE_LIMIT = 1000
